spring:
  application:
    name: energy-analysis-api

  datasource:
    url: jdbc:postgresql://localhost:5432/energiai
    username: postgres
    password: cp1av5zs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    api-docs:
        path: /v3/api-docs

server:
  port: 8080